config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  get 'static_pages/home'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :notes do
    resources :shares
  end
end

app/views/shared/_action_buttons.html.erb
<% note = locals[:note] %>

<div class="row js-action-buttons">
  <div class="col s12 horizontal js-note--action-buttons">
    <% if note.update? %>
      <%= link_to(edit_note_path(note), class: 'btn-floating blue') do %>
        <i class="material-icons">edit</i>
      <% end %>
    <% end %>

    <% if note.delete? %>
      <a class="btn-floating js-note-action-btn grey" data-action=".js-delete-action">
        <i class="material-icons">delete</i>
      </a>
    <% end %>

    <% if note.update? %>
      <a class="btn-floating js-note-action-btn green" data-action=".js-tag-action">
        <i class="material-icons">label</i>
      </a>
    <% end %>

    <% if note.share? %>
      <a href="#!" class="btn-floating js-note-action-btn red" data-action=".js-share-action">
        <i class="material-icons">share</i>
      </a>
    <% end %>
  </div>
</div>

<div class="row hide js-delete-action">
  <%= form_for note, html: { class: 'col s12' }, method: :delete do |f| %>
    <p>Are you sure you want to delete this note?</p>
    <%= f.submit 'Yes', class: 'btn' %>
    <%= f.button 'No', class: 'btn grey js-cancel-button' %>
  <% end %>
</div>

<div class="row hide js-tag-action">
  <div class="chips" data-note-id="<%= note.id %>"></div>
  <input type="button" class="btn grey js-cancel-button" value="Ok"/>
</div>

<%= render 'shared/sharing_section', locals: { note: note } %>

app/views/shared/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Notekeeper</a>

    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if logged_in? %>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Signup', signup_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_message_error.html.erb
<% if flash[:errors] %>
<div class="row">
  <div class="col s12 red-text">
    The form contains <%= pluralize(flash[:errors].count, "error") %>.
    <ul>
    <% flash[:errors].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_sharing_section.html.erb
<% note = locals[:note] %>
<% items = note.share_list %>

<div class="row hide js-share-action">
  <div class="col s12">
    <ul class="collection">
      <% items.each do |item| %>
        <li class="collection-item">
          <%= form_for :share, url: "/notes/#{note.id}/shares/#{item.id}", method: :delete do |f| %>
            <button type="submit" class="secondary-content" style="border: none;">
              <i class="material-icons white-text circle red">delete</i>
            </button>
            
            <span class="title"><%= item[:email] %></span><br/>
            <span class="grey-text">(<%= item[:permission] %>)</span>
          <% end %>
        </li>
      <% end %>

        <li class="col s12 collection-item">

          <%= form_for :share, url: "notes/#{note.id}/shares", method: :post do |f| %>
            <div class="input-field col s12">
              <%= f.email_field :email %>
              <%= f.label :email %>
            </div>

            <% radio_id = "#{note.id}_permission" %>
            <% PermissionType.all.each do |p| %>
              <p>
                <%= radio_button_tag('share[permission]', p.permission, false, id: "#{radio_id}_#{p.permission}") %>
                <%= label_tag("#{radio_id}_#{p.permission}", p.permission) %>
              </p>
            <% end %>

            <div class="input-field col s12">
              <%= f.submit 'Share', class: 'btn' %>
              <%= f.button 'Cancel', class: 'btn grey js-cancel-button' %>
            </div>
          <% end %>
        </li>
    </ul>
  </div>
</div>